language: python
python:
  - "3.6"
# command to install dependencies
services: postgresql
env:
  global: 
    - SECRET=mysecretword
before_script:
  - psql -c 'create database test_db;' -U postgres
  - psql -c "ALTER USER "postgres" WITH PASSWORD 'winston77';" -U postgres
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls --quiet
# command to run tests
script: 
-nosetests/tests
-nosetests --with-coverage --cover-package=app

after_success: coveralls