language: python
python:
  - "3.6"
# command to install dependencies
services: postgresql
env:
  global: 
    - SECRET=my-strings-for-setting-secret
    - DATABASE_URL=postgresql://postgres:@localhost/new_test_db
before_script:
  - psql -c 'create database new_test_db;' -U postgres
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls 
# command to run tests
script: 
  - pytest
  - nosetests --with-coverage
after_success: coveralls