language: python
python:
  - "3.6"
# command to install dependencies
services: postgresql
before_script: createdb database_test

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls --quiet
# command to run tests
script: nosetests --with-coverage
after_success: coveralls